### ISSUE TITLE
Тест

### ISSUE THREAD

**Issue by Fodense** [7VeDMaK/clevertec-gradle#1]
Тест должен отвечать за одно действие, а не за всё что только можно)

Лучшим решение в данном случае было бы разделить этот тест на два: положительные кейсы и отрицательные при этом используя @ParameterizedTest

https://github.com/7VeDMaK/clevertec-gradle/blob/b2657eff0de9e9d8b3fe297ccb93c88c34d602c4/core/src/test/java/org/example/UtilsTest.java#L11

**Comment by 7VeDMaK** [comment]
Good point, thank you. And I still have no idea how to use tests better. I'm waiting for the JUnit lecture! :D

My last commit solved this issue.
